#!/bin/bash
# Copyright 2019 Ignasi Barrera
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

SITE_ROOT=$(dirname ${BASH_SOURCE[0]})/../..
cd ${SITE_ROOT}

echo "Rendering site..."
make render

echo "Adding generated site files to the commit..."
git add docs
